[toolchain]
channel = "stable"
components = [
    "clappy",
    # "miri",
    "rustfmt",
]
targets = [
    "aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabihf",
    "x86_64-unknown-linux-musl",
]
