ARG BASE_IMAGE=rust:1.54.0-buster
FROM $BASE_IMAGE
RUN apt-get update && \
    apt-get install -y \
        binutils-aarch64-linux-gnu \
        binutils-arm-linux-gnueabihf \
        binutils-x86-64-linux-gnu \
        docker.io \
        jq \
        musl-tools \
        && \
    apt-get clean && \
    rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/
RUN cargo install --locked cross
WORKDIR /k8s_api_gateway_proxy_mesh_test
